name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Bundle install
        run: bundle install

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Install npm packages
        run: npm ci

      - name: Build site
        run: bundle exec jekyll build

      - name: Generate favicons
        run: ./favicon/generate-favicons.sh

      - name: Archive site
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Download site artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: _site/

      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
          rsync -avz --delete -e "ssh -i ~/.ssh/deploy_key" _site/ "$DEPLOY_USER@$DEPLOY_HOST:/home/ben/srv/static-site/"
